---
seasons:
  - name: Corinthians
    start: Aug 1, 2025
    days: 365
    meets:

      - name: Scramble
        start: Sep 20 2025 8 AM PDT
        special_material: 1 Cor 1-4
        deadline: 0
        host:
            name: Lutheran Church of the Master
            url: https://lcmcda.org
            address: 4800 N Ramsey Rd, Coeur d'Alene ID 83815
            lunch: true
        notes: |
            - Site of Coeur d'Alene Classical Christian School
            - No registration required

      - name: Meet 1
        start: Oct 25 2025 8 AM PST
        new_material: 1 Cor 1-9
        host:
            name: Kamiah Bible Church
            url: https://cityofkamiah.org/kamiah-bible-church
            address: 521 10th St, Kamiah ID 83536
            housing: true
            lunch: true

      - name: Meet 2
        region: WWA

      - name: Meet 3
        start: Jan 3 2026 9 AM PST
        new_material: 1 Cor 13-16
        host:
            name: Bridge Bible Fellowship
            url: https://bridgebible.org
            address: 960 W Palouse River Dr, Moscow ID 83843
            lunch: true
        notes: |
            - [Additional Information Flyer](/seasons/2025_cor/2025-01-03_meet_flyer.pdf)

      - name: Meet 4
        region: WWA

      - name: Meet 5
        region: WWA

      - name: Championships
        region: WWA
